### ISSUE TITLE
Is it possible to sync to a subfolder

### ISSUE THREAD

**Issue by dapf27** [EvotecIT/O365Synchronizer#1]
Hi,
I would like to use your nice module, but it would be nice to sync all that many contacts to a subfolder so it would be easier for the users to differentiate which are their own contacts and which are out of GAL.
I saw in your code that the "ParentFolderId" is there, but would it be possible to use a param at the "Sync-O365PersonalContact" to create or update such a subfolder?
Thank you!

**Comment by PrzemyslawKlys** [comment]
Probably there is, but I've not played with it. It would require additional logic, checking if folder exists, creating it and so on. Doable, but requires some work.

**Comment by IE-MP** [comment]
Would love that functionality as well, if it's in your plans.

**Comment by PrzemyslawKlys** [comment]
I need to sit down to it and fix it. So ye, it's in plans.

**Comment by PrzemyslawKlys** [comment]
This feature will be in new release. Ability to sync to a folder. The folder will be created before creating contacts. This release also allows to use filters.

```powershell
    Sync-O365PersonalContact -UserId 'przemyslaw.klys@evotec.pl' -MemberTypes 'Contact', 'Member' -GuidPrefix 'O365Synchronizer' -PassThru {
        Sync-O365PersonalContactFilter -Type Include -Property 'CompanyName' -Value 'Evotec*','Ziomek*' -Operator 'like'
        Sync-O365PersonalContactFilterGroup -Type Include -GroupID 'e7772951-4b0e-4f10-8f38-eae9b8f55962'
    } -FolderName 'O365Sync' -WhatIf | Format-Table
```

Please keep in mind that if you are switching from non-folder sync you first need to remove old syncs, or you will get sort of duplicates. 

I've also added ability to clear contacts from that folder, and clear & delete the folder itself. 

```powershell
Clear-O365PersonalContact -Identity 'przemyslaw.klys@evotec.pl' -GuidPrefix 'O365Synchronizer' -FolderName 'O365' -WhatIf

Clear-O365PersonalContact -Identity 'przemyslaw.klys@evotec.pl' -GuidPrefix 'O365Synchronizer' -FolderName 'O365Sync' -FolderRemove -WhatIf
```

Of course please make sure to use WhatIf, testing to rule out potential bugs.

**Comment by dapf27** [comment]
Thanks for your work. But I think it destroyed some things.
Work good:
- Creating folder and sync contacts to this folder

Don't work:
- Deleting contacts
- Updating contacts (creates duplicates)
- Deleting folder (still exists in OWA as category)

**Comment by PrzemyslawKlys** [comment]
Updating and deleting contacts is based on unique id, if you are using same ID and guidprefix there will be duplicates and it will try to update in the main folder

**Comment by dapf27** [comment]
Yes before starting it was all clean.
I had now, that the update worked and at next run it didn't work, some users were updated and some got a duplicate.
Running two times this: Sync-O365PersonalContact -UserId '*@*' -MemberTypes 'Member' -GuidPrefix 'O365Synchronizer' -FolderName 'O365Sync'
It shouldn't create duplicates.
The Clear-O365PersonalContact deletes only 10 contacts per run.
And if I use the -FolderRemove parameter it says: Failed to remove folder O365Sync from *@* because: [ErrorCannotDeleteObject] : Object cannot be deleted.

**Comment by PrzemyslawKlys** [comment]
This should fix it. 1.0.1. I forgot using -All switch which I guess would cause duplicates if the order of gathered objects was not the same, and it would cause clear to clear 10 at a time when using folder.

**Comment by dapf27** [comment]
Thanks for the update but I still get duplicates and with Clear-O365PersonalContact it deletes still only 10 contacts per run.

**Comment by PrzemyslawKlys** [comment]
Which version are you using?

**Comment by dapf27** [comment]
```
ModuleType    Version    PreRelease   Name
----------    -------    ----------   ----
Script        1.0.2                   O365Synchronizer
```

What logs do you need?

First run:
![image](https://github.com/user-attachments/assets/8be43760-86dd-42b1-8b4d-b434fdf77115)
Second run:
![image](https://github.com/user-attachments/assets/9c520ff7-79e4-4484-a0b6-d8e18438c687)

Clear with only 10:
![image](https://github.com/user-attachments/assets/0df4d96b-cdd9-4fc5-b376-1988f620652b)

**Comment by timecop77** [comment]
I have the same issue when I work with Folders. First Sync (e.g. 300 contacts) works well. Second sync -> the script says the User have only 10 contacts and will process 300 contacts. So I have 290 duplicates. 

But all work fine without separate Folders (standard contact folder)

I use the lastest Version 1.0.2

**Comment by PrzemyslawKlys** [comment]
The problem comes from:

```powershell
Get-MgUserContactFolder -UserId $Identity -Filter "DisplayName eq '$FolderName'" -ExpandProperty Contacts -ErrorAction Stop -ALl
``` 

The ALL switch doesn't do anything. So I need to find proper way to do this.

**Comment by PrzemyslawKlys** [comment]
This release should fix this issue:
- https://github.com/EvotecIT/O365Synchronizer/releases/tag/v1.0.3

**Comment by dapf27** [comment]
It works great, thank you, but...
I'm sorry!
Only one little error while also deleting the folder.
![image](https://github.com/user-attachments/assets/4c8f25c6-5356-4e2e-b614-c637c685bace)

**Comment by PrzemyslawKlys** [comment]
Please don't resurect issues like that. Open an issue if you  have a problem
